### ISSUE TITLE
No me borres

### ISSUE THREAD

**Issue by mayax007** [Kowlan96/repoCharlaGit#2]
No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo No me borre, no hay repo

**Comment by Kowlan96** [comment]
Está arreglado :D
